### PR TITLE
FIX: remove cap on `mdit-py-plugins` version

### PR DESCRIPTION
**Pull request by kdeldycke**
Closes: https://github.com/executablebooks/mdformat-myst/issues/27

### CODE REVIEW

**Comment by MattKang** [comment]
Would love if this could get merged. Blocking this being packaged into `nix`

**Comment by MattKang** [comment]
@jpmckinney @hukkin @hukkinj1 @chrisjsewell are any of you still maintaining this?

**Comment by KyleKing** [comment]
As of ~3 minutes ago, I've been added as a new maintainer!

I'm getting up to speed on open PRs and tickets, but I'll start with this one

**Comment by KyleKing** [comment]
I'll make a release by tomorrow because there are some maintenance updates required for CI/CD first

**Comment by chrisjsewell** [comment]
Thanks @KyleKing, yeh I'm interested in this, but don't have the capacity to maintain.
(I am maintaining `mdit-py-plugins` though, so definitely get a review before merging anything there 😉)

**Comment by kdeldycke** [comment]
Thanks @KyleKing for the merge and congrats on the new promotion! 🥳

**Pull request merged**
